//! This module contains FFI bindings to Zsh's C API.
//!
//! These bindings are automatically generated by the `bindgen` tool from Zsh's C header files.
//! They provide the raw, unsafe interfaces necessary to interact with the Zsh core from Rust.
//!
//! The `#[allow(...)]` attributes are used to suppress various linter warnings that commonly
//! arise from `bindgen`-generated code, such as non-idiomatic naming conventions, unused code,
//! and C-specific type representations.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(unnecessary_transmutes)]
#![allow(unused)]
#![allow(clippy::all)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
